services:
  - type: web
    name: job-crawler
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/main.js
    envVars:
      - key: NODE_ENV
        value: production
